name: Test and Build Android App

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: SyzygyEventApp
      - name: Test with Gradle
        run: ./gradlew test
        working-directory: SyzygyEventApp
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: SyzygyEventApp/app/build/reports/tests/testDebugUnitTest/
    continue-on-error: false

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: SyzygyEventApp
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: SyzygyEventApp
      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: SyzygyEventApp
      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: SyzygyEventApp/app/build/outputs/apk/debug/*.apk
      - name: Upload Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: SyzygyEventApp/app/build/outputs/apk/release/*.apk