name: Android Instrumented Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Enable KVM (hardware acceleration for virtualization)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm

      - name: Create and start the Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: pixel_6
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumented-test-report
          path: app/build/reports/androidTests/connected/
