name: Android Instrumentation Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: Run Instrumentation Tests
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build debug APK and test APK
      run: |
        ./gradlew assembleDebug assembleAndroidTest

    - name: Run instrumentation tests
      uses: android-actions/run-android-emulator@v2
      with:
        api-level: 36
        script: ./gradlew connectedAndroidTest
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: app/build/reports/
        retention-days: 7