name: Android Instrumentation Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: Run Instrumentation Tests
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: SyzygyEventApp

    - name: Build debug APK and test APK
      run: |
        ./gradlew assembleDebug assembleAndroidTest
      working-directory: SyzygyEventApp

    - name: Create and start the Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 36
        target: google_apis
        arch: x86_64
        profile: pixel_6
        script: ./SyzygyEventApp/gradlew connectedDebugAndroidTest
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: SyzygyEventApp/app/build/reports/